import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import type { AppSettings, KiroUsage, ProviderKind, ThemePreference, UsageSnapshot } from "../shared/types";
import "./styles.css";
import "./tooltip.css";
import "./compact.css";

const date = new Date(), currentMonth = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
const empty: UsageSnapshot = { kiro: { status: "not-found", today: 0, week: 0, month: 0, currentMonth, months: [], allTime: 0, sessions: 0, turns: 0, quota: null, updatedAt: null, message: null }, codex: { status: "not-found", windows: [], updatedAt: null, message: null } };
function App(): React.JSX.Element {
  const [usage, setUsage] = useState(empty), [settings, setSettings] = useState<AppSettings>({ enabledProviders: ["Kiro"], theme: "system", launchAtLogin: false }), [settingsOpen, setSettingsOpen] = useState(false), [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([window.limia.getUsage(), window.limia.getSettings()]).then(([u,s]) => { setUsage(u); setSettings(s); }).finally(() => setLoading(false)); const a = window.limia.onUsageChanged(setUsage), b = window.limia.onSettingsChanged(setSettings), c = window.limia.onShowUsage(() => setSettingsOpen(false)); return () => { a(); b(); c(); }; }, []);
  useEffect(() => { document.documentElement.dataset.theme = settings.theme; }, [settings.theme]);
  useEffect(() => { const providerCount = settings.enabledProviders.length; const height = settingsOpen ? 258 : providerCount === 0 ? 112 : Math.min(320, 64 + providerCount * 112); void window.limia.resizePopup(height); }, [settingsOpen, settings.enabledProviders]);
  const refresh = async () => { setLoading(true); try { setUsage(await window.limia.refreshUsage()); } finally { setLoading(false); } };
  return <main><nav><span>{settingsOpen ? "Settings" : "Usage"}</span><div><img className="limia-motion" src="./assets/limia-animated.svg" alt=""/><button onClick={refresh} aria-label="Refresh"><Refresh spinning={loading}/></button><button className={settingsOpen ? "active" : ""} onClick={() => setSettingsOpen(!settingsOpen)} aria-label="Settings"><Gear/></button></div></nav>{settingsOpen ? <Settings settings={settings} onChange={setSettings}/> : <Dashboard usage={usage} enabled={settings.enabledProviders}/>}</main>;
}
function Dashboard({ usage, enabled }: { usage: UsageSnapshot; enabled: ProviderKind[] }): React.JSX.Element { return <section className="providers">{enabled.length === 0 && <p className="empty">Enable a provider in settings.</p>}{enabled.includes("Kiro") && <KiroRow usage={usage.kiro}/>} {enabled.includes("Codex") && <CodexRow usage={usage.codex}/>}</section>; }
function KiroRow({ usage }: { usage: KiroUsage }): React.JSX.Element { const quota = usage.quota; return <ProviderRow icon="./assets/kiro.png" name="Kiro" control={<span className="current-month">{monthLabel(usage.currentMonth)}</span>}>{usage.status === "ready" ? <div className="metrics">{quota ? <RingMetric label="Monthly credits" usedPercent={quota.used / quota.limit * 100} tooltip={(clock) => `${format(quota.used)} of ${format(quota.limit)} credits used · ${quota.resetAt ? resetDescription(quota.resetAt, clock) : "Reset unavailable"}`}/> : <RingMetric label="Credits used" creditValue={usage.month} tooltip={() => "Kiro CLI does not expose the plan limit or reset time."}/>}</div> : <ErrorText text={usage.message}/>}</ProviderRow>; }
function CodexRow({ usage }: { usage: UsageSnapshot["codex"] }): React.JSX.Element { return <ProviderRow icon="./assets/codex.png" name="Codex">{usage.status === "ready" ? <div className="metrics">{usage.windows.map((item) => <RingMetric key={item.label} label={item.label} usedPercent={item.usedPercent} tooltip={(clock) => `${Math.round(item.usedPercent)}% used · ${item.resetAt ? resetDescription(item.resetAt, clock) : "Reset unavailable"}`}/>)}</div> : <ErrorText text={usage.message}/>}</ProviderRow>; }
function RingMetric({ label, usedPercent, creditValue, tooltip }: { label: string; usedPercent?: number; creditValue?: number; tooltip: (clock: number) => string }): React.JSX.Element { const [showUsed, setShowUsed] = useState(false), [clock, setClock] = useState(Date.now()), percentage = usedPercent === undefined ? null : showUsed ? usedPercent : 100 - usedPercent; useEffect(() => { const timer = window.setInterval(() => setClock(Date.now()), 30_000); return () => window.clearInterval(timer); }, []); const interactive = usedPercent !== undefined; return <button className="metric" onClick={() => interactive && setShowUsed(!showUsed)} aria-label={`${label}, ${percentage === null ? `${format(creditValue ?? 0)} credits used` : `${Math.round(percentage)} percent ${showUsed ? "used" : "remaining"}`}`}><div className={`ring ${percentage === null ? "credit-ring" : ""}`} style={{"--progress":`${(percentage ?? 100) * 3.6}deg`} as React.CSSProperties}><strong>{percentage === null ? format(creditValue ?? 0) : `${Math.round(percentage)}%`}</strong></div><span>{label}</span><small>{percentage === null ? "limit unavailable" : showUsed ? "used" : "remaining"}</small><span className="reset-tooltip">{tooltip(clock)}</span></button>; }
function ProviderRow({ icon, name, control, children }: { icon: string; name: string; control?: React.ReactNode; children: React.ReactNode }): React.JSX.Element { return <article><header><div><img src={icon}/><strong>{name}</strong></div>{control}</header>{children}</article>; }
function Settings({ settings, onChange }: { settings: AppSettings; onChange: (settings: AppSettings) => void }): React.JSX.Element { const toggle = async (kind: ProviderKind, enabled: boolean) => onChange(await window.limia.setProviderEnabled(kind, enabled)), theme = async (value: ThemePreference) => onChange(await window.limia.setTheme(value)), launch = async (enabled: boolean) => onChange(await window.limia.setLaunchAtLogin(enabled)); return <section className="settings"><h2>Providers</h2><Toggle icon="./assets/kiro.png" label="Kiro" checked={settings.enabledProviders.includes("Kiro")} onChange={(v) => toggle("Kiro",v)}/><Toggle icon="./assets/codex.png" label="Codex" checked={settings.enabledProviders.includes("Codex")} onChange={(v) => toggle("Codex",v)}/><h2>General</h2><Toggle label="Open at login" checked={settings.launchAtLogin} onChange={launch}/><h2>Appearance</h2><div className="themes">{(["system","light","dark"] as ThemePreference[]).map((value) => <button className={settings.theme === value ? "selected" : ""} onClick={() => theme(value)} key={value}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div><p className="credit">Created by Sidney Lima</p></section>; }
function Toggle({icon,label,checked,onChange}:{icon?:string;label:string;checked:boolean;onChange:(value:boolean)=>void}):React.JSX.Element{return <label className="toggle"><span>{icon&&<img src={icon}/>} {label}</span><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/><i/></label>}
function ErrorText({text}:{text:string|null}):React.JSX.Element{return <p className="error">{text??"No usage available."}</p>}
function Refresh({spinning}:{spinning:boolean}):React.JSX.Element{return <svg className={spinning?"spin":""} viewBox="0 0 24 24"><path d="M20 11a8 8 0 1 0-2.3 5.7M20 4v7h-7"/></svg>}
function Gear():React.JSX.Element{return <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/></svg>}
function format(v:number):string{return new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(v)} function monthLabel(key:string):string{const[y,m]=key.split("-").map(Number);return new Intl.DateTimeFormat(undefined,{month:"short",year:"numeric"}).format(new Date(y,m-1,1))}
function resetDescription(value:string,now:number):string{const reset=new Date(value),remaining=Math.max(0,reset.getTime()-now),minutes=Math.ceil(remaining/60_000);if(minutes<=0)return "Resets now";if(minutes<60)return `Resets in ${minutes} min`;if(minutes<1_440){const hours=Math.floor(minutes/60),rest=minutes%60;return `Resets in ${hours}h${rest?` ${rest}m`:""}`;}const weekday=new Intl.DateTimeFormat("en-US",{weekday:"short"}).format(reset),month=new Intl.DateTimeFormat("en-US",{month:"short"}).format(reset),day=reset.getDate(),time=new Intl.DateTimeFormat("en-US",{hour:"2-digit",minute:"2-digit",hour12:false}).format(reset);return `Resets ${weekday}, ${month} ${day} at ${time}`}
createRoot(document.getElementById("root")!).render(<App/>);
